name: Android CI

on:
push:
  branches: [master]
pull_request:
  branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v1
        
        - name : Run Tests
          run: ./gradlew test
         
         -name: Build Project
          run: ./gradlew assemble

        - name : Run a one-line script
          run: echo Hello world

          - name: Run a multi-line script
            run: |
                  echo Run other lines
                  echo test, deploy and built

         
        with:
          java-version: 1.8

             

