name: Android CI

on:
  push:
    branches:
      - master
      - testapk   # Add the 'action' branch here

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/debug/app-debug.apk  # Update the path to point to the debug APK location
          distribution: public
