name: Android CI

on:
  push:
    branches:
      - master
      - testapk   # Add the 'action' branch here

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build the app bundle
        run: ./gradlew bundleDebug

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-debug   # Add a name for the artifact
          path: app/debug/*.aab
