name: Android CI

on:
  push:
   branches: [ actionsdemo ]
  pull_request:
   branches: [ actionsdemo ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello world

      - name: Run a multi-line script
        run: |
          echo Run other lines
          echo test, deploy and built

      - name: Run Lint
        run: ./gradlew lint

      - name: Upload a html file
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html



