name: Android CI

on:
  push:
    branches:
      - master
      - testapk   # Add the 'action' branch here

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
         name: app
         path: app/build/outputs/bundle/debug/app-release.aab
