name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
          run: ./gradlew assembleDebug    # Change this line to assembleDebug for debug APK

            - name: Upload AppBundle
              uses: actions/upload-artifact@v2
              with:
                name: app-debug
                path: app/debug/app-debug.abb   # Point to the debug APK location

